# Generated by Django 3.1.7 on 2021-05-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productimage/')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(max_length=5)),
            ],
        ),
    ]
