# Generated by Django 3.1.7 on 2021-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210519_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='image',
            field=models.ImageField(upload_to='media/media/productimage/'),
        ),
    ]
