# Generated by Django 4.2.1 on 2023-09-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_auto_20210522_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttable",
            name="image",
            field=models.ImageField(upload_to="media/productimage/"),
        ),
    ]
