# Generated by Django 3.1.7 on 2021-05-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='usertable',
            name='address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
