# Generated by Django 3.1.7 on 2021-05-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20210519_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
